name: build book
description: build book
inputs:
  config:
    description: config file
    required: true
    default: config.yml
runs:
  using: composite
  steps:
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - run: echo "REVIEW_VERSION=`bundle info review --version | cut -d '.' -f 1-2`" >> $GITHUB_ENV
      shell: bash
    - uses: masarakki/docker-alias@v3
      with:
        image: vvakame/review:${{ env.REVIEW_VERSION }}
        commands: review-pdfmaker
    - run: rm `bundle exec which review-pdfmaker`
      shell: bash
    - run: bundle exec rake pdf
      shell: bash
      env:
        REVIEW_CONFIG_FILE: ${{ inputs.config }}
