name: build
on:
  pull_request:
    branches: "**"
defaults:
  run:
    working-directory: ./test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          working-directory: ./test
      - run: test -e Rakefile
      - run: test -e Gemfile
      - run: test -e Gemfile.lock

  without-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          working-directory: ./test
  with-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          config: config.pdf.yml
          working-directory: ./test
