name: build
on:
  pull_request:
    branches: "**"
defaults:
  run:
    working-directory: ./test
jobs:
  without-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./build
  with-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./build
        with:
          config: config.pdf.yml
